### ISSUE TITLE
Possible malware in bioformats-examples-master.zip

### ISSUE THREAD

**Issue by scuniff** [ome/bio-formats-examples#122] opened 2024-01-18 07:42 UTC
I tried downloading **bioformats-examples-master.zip** and my Windows Defender quarantined it after it downloaded.

The attached screenshot is the entry in Event Viewer and you'll see **bioformats-examples-master.zip** referenced in the middle of the screen in blue text.

I will be seeing some cyber security folks later tomorrow afternoon and see what they have to say.

![IMG_8995](https://github.com/ome/bio-formats-examples/assets/40019379/6fdcae3b-3777-47ff-8156-eaa3d8ed0e4e)

**Comment by melissalinkert** [comment] 2024-01-18 16:02
Thanks for reporting, @scuniff. I was not able to immediately reproduce this issue on Windows 10, with a fully updated Windows Defender. The file was neither quarantined upon download nor flagged when it was scanned manually.

I downloaded the zip by selecting `Code` > `Local` > `Download ZIP` on https://github.com/ome/bio-formats-examples. The checksum is:

```
PS C:\Users\melissa\Downloads> Get-FileHash -Path .\bio-formats-examples-master.zip

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          1955D077B106C4CACB2949DD0E3789DB9BFC4409007DA4213ED7A0B22B4E304B       C:\Users\melissa\Downloads\bi...
```

Could you please let us know how you downloaded `bio-formats-examples-master.zip` and what checksum you see?

**Comment by melissalinkert** [comment] 2024-04-08 14:27
Closing since this still appears to be a false positive, but let us know @scuniff if you still see a problem.

**Closed by melissalinkert** 2024-04-08 14:27 UTC
